const KEY='myplanner.web.v1';
const praise=['Ты большая молодец!','Готово — ещё один шаг!','Отличная работа!','Так держать!','Ты справилась!','Маленькая победа — тоже победа!','План выполнен — умница!','Ещё один пункт закрыт!','Вот это продуктивность!','Ты двигаешься вперёд!'];
const icons=['✓','⭐','❤️','🏠','💼','🧠','🛒','🏃','📚','🎯','🧹','💡'];
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{tasks:[],groups:[{id:'g1',name:'Личное',icon:'❤️',color:'#2563eb'},{id:'g2',name:'Работа',icon:'💼',color:'#7c3aed'}],notes:[],achievements:[],events:[],view:'day',date:iso(new Date()),query:'',filter:'all',group:'all'};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}function iso(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}function fmtDate(s){return new Date(s+'T12:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})}function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function parseQuick(s){const m=s.match(/^(\d{1,2}):(\d{2})\s+(.+)$/);return m?{time:`${m[1].padStart(2,'0')}:${m[2]}`,title:m[3]}:{time:'',title:s}}
function taskDate(t){return t.date||state.date}
function filteredTasks(){return state.tasks.filter(t=>taskDate(t)===state.date).filter(t=>state.group==='all'||t.groupId===state.group).filter(t=>!state.query||t.title.toLowerCase().includes(state.query.toLowerCase())).filter(t=>state.filter==='all'||(state.filter==='done'?t.done:state.filter==='important'?t.important:state.filter==='active'&&!t.done)).sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'))}
function app(){document.querySelector('#app').innerHTML=`<main class="app"><header class="top"><div class="toprow"><div><div class="title">MyPlanner</div><div class="sub">${fmtDate(state.date)}</div></div><button onclick="quick()">+ Быстро</button></div><div class="nav">${['day','week','month','focus','stats','notes'].map(x=>`<button class="${state.view===x?'active':''}" onclick="setView('${x}')">${({day:'День',week:'Неделя',month:'Месяц',focus:'Фокус',stats:'Статистика',notes:'Заметки'})[x]}</button>`).join('')}</div></header>${renderView()}<button class="fab" onclick="editTask()">+</button></main>`;if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
function setView(v){state.view=v;save();app()}
function renderView(){if(state.view==='day')return day();if(state.view==='week')return week();if(state.view==='month')return month();if(state.view==='focus')return focus();if(state.view==='stats')return stats();return notes()}
function day(){const ts=filteredTasks();const done=ts.filter(t=>t.done).length;return `<section class="card"><div class="between"><div><b>План на сегодня</b><div class="small">${done} из ${ts.length} выполнено</div></div><b>${ts.length?Math.round(done/ts.length*100):0}%</b></div><div class="progress"><i style="width:${ts.length?done/ts.length*100:0}%"></i></div></section><section class="card"><div class="toolbar"><button onclick="shift(-1)">←</button><button onclick="state.date=iso(new Date());save();app()">Сегодня</button><button onclick="shift(1)">→</button><input class="input" style="flex:1;min-width:130px" placeholder="Поиск" value="${esc(state.query)}" oninput="state.query=this.value;app()"></div><div class="toolbar" style="margin-top:8px">${['all','active','important','done'].map(f=>`<button class="${state.filter===f?'primary':''}" onclick="state.filter='${f}';app()">${({all:'Все',active:'Активные',important:'Важные',done:'Готово'})[f]}</button>`).join('')}</div><div class="toolbar" style="margin-top:8px">${groupButtons()}</div></section>${ts.length?ts.map(taskCard).join(''):`<div class="empty">На этот день дел пока нет.<br>Нажми + и добавь первое.</div>`}`}
function groupButtons(){return `<button class="${state.group==='all'?'primary':''}" onclick="state.group='all';app()">Все группы</button>`+state.groups.map(g=>`<button class="${state.group===g.id?'primary':''}" onclick="state.group='${g.id}';app()">${g.icon} ${esc(g.name)}</button>`).join('')}
function taskCard(t){const g=state.groups.find(x=>x.id===t.groupId);return `<article class="card"><div class="task ${t.done?'done':''}"><button class="check ${t.done?'done':''}" onclick="toggle('${t.id}')">${t.done?'✓':''}</button><div class="taskmain" onclick="editTask('${t.id}')"><div class="tasktitle">${esc(t.title)}</div><div class="meta">${t.time?`<span class="pill">⏰ ${t.time}</span>`:''}${t.important?'<span class="pill">⭐ Важное</span>':''}${t.priority?`<span class="pill">${t.priority}</span>`:''}${g?`<span class="pill">${g.icon} ${esc(g.name)}</span>`:''}${t.repeat?`<span class="pill">🔁 ${esc(t.repeat)}</span>`:''}</div></div><button onclick="editTask('${t.id}')">⋯</button></div></article>`}
function shift(n){const d=new Date(state.date+'T12:00');d.setDate(d.getDate()+n);state.date=iso(d);save();app()}
function week(){const d=new Date(state.date+'T12:00');const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);let out='<section class="card"><div class="between"><button onclick="shift(-7)">←</button><b>Неделя</b><button onclick="shift(7)">→</button></div></section>';for(let i=0;i<7;i++){const x=new Date(d);x.setDate(d.getDate()+i);const s=iso(x),ts=state.tasks.filter(t=>taskDate(t)===s);out+=`<section class="card"><div class="between"><b>${x.toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'})}</b><button onclick="state.date='${s}';state.view='day';app()">Открыть</button></div>${ts.slice(0,4).map(taskCard).join('')}${ts.length>4?`<div class="small">+${ts.length-4} ещё</div>`:''}</section>`}return out}
function month(){const d=new Date(state.date+'T12:00'),y=d.getFullYear(),m=d.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate();let h='<section class="card"><div class="between"><button onclick="monthShift(-1)">←</button><b>'+d.toLocaleDateString('ru-RU',{month:'long',year:'numeric'})+'</b><button onclick="monthShift(1)">→</button></div><div class="calendar">'+['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<div class="calhead">${x}</div>`).join('');for(let i=0;i<start;i++)h+='<div></div>';for(let n=1;n<=days;n++){const s=iso(new Date(y,m,n)),ts=state.tasks.filter(t=>taskDate(t)===s);h+=`<div class="day ${s===state.date?'sel':''} ${s===iso(new Date())?'today':''}" onclick="state.date='${s}';state.view='day';app()"><b>${n}</b><div>${ts.slice(0,5).map(t=>`<span class="dot" title="${esc(t.title)}" style="background:${t.color||'#2563eb'}"></span>`).join('')}</div></div>`}return h+'</div></section>'}function monthShift(n){const d=new Date(state.date+'T12:00');d.setMonth(d.getMonth()+n,1);state.date=iso(d);save();app()}
function focus(){const all=state.tasks.filter(t=>!t.done);const score=t=>(t.important?5:0)+(t.priority==='Высокий'?4:t.priority==='Средний'?2:0)+(taskDate(t)<iso(new Date())?6:0);const top=all.sort((a,b)=>score(b)-score(a)).slice(0,3);return `<section class="card"><h2>🎯 Фокус</h2><div class="small">До трёх дел, которым сейчас стоит уделить внимание.</div></section>${top.length?top.map(taskCard).join(''):'<div class="empty">Фокус свободен 🎉</div>'}<section class="card"><b>Последние выполненные</b>${state.events.slice(-5).reverse().map(e=>`<p class="small">✓ ${esc(e.title)} — ${new Date(e.at).toLocaleString('ru-RU')}</p>`).join('')||'<p class="small">Пока нет выполненных дел.</p>'}</section>`}
function stats(){const total=state.tasks.length,done=state.tasks.filter(t=>t.done).length;const byTitle={};state.events.forEach(e=>byTitle[e.title]=(byTitle[e.title]||0)+1);const top=Object.entries(byTitle).sort((a,b)=>b[1]-a[1]).slice(0,5);return `<section class="grid"><div class="card"><div class="stats">${total}</div><div class="small">Всего дел</div></div><div class="card"><div class="stats">${done}</div><div class="small">Выполнено</div></div><div class="card"><div class="stats">${total?Math.round(done/total*100):0}%</div><div class="small">Процент</div></div><div class="card"><div class="stats">${state.events.length}</div><div class="small">Выполнений</div></div></section><section class="card"><h3>🏆 Часто выполняемые</h3>${top.map(([t,n])=>`<div class="between"><span>${esc(t)}</span><b>${n}</b></div>`).join('')||'<div class="small">Пока недостаточно данных.</div>'}</section><section class="card"><h3>🏅 Достижения</h3>${achievements().map(a=>`<p>${a}</p>`).join('')}</section>`}
function achievements(){const n=state.events.length;return [n>=1?'🥇 Первое выполнение':'🔒 Первое выполнение',n>=10?'🔥 10 выполнений':'🔒 10 выполнений',n>=50?'💎 50 выполнений':'🔒 50 выполнений']}
function notes(){return `<section class="card"><div class="between"><h2>📝 Заметки</h2><button onclick="newNote()">+ Заметка</button></div></section>${state.notes.map(n=>`<article class="card"><div class="between"><b>${esc(n.title)}</b><button class="danger" onclick="delNote('${n.id}')">Удалить</button></div><p>${esc(n.text)}</p><div class="small">${new Date(n.updated).toLocaleString('ru-RU')}</div></article>`).join('')||'<div class="empty">Заметок пока нет.</div>'}`}
function modal(html){const d=document.createElement('div');d.className='modal';d.innerHTML=`<div class="sheet">${html}</div>`;d.onclick=e=>{if(e.target===d)d.remove()};document.body.append(d);return d}
function quick(){modal(`<div class="between"><h2>Быстрое дело</h2><button onclick="this.closest('.modal').remove()">✕</button></div><div class="field"><label>Например: 18:30 Позвонить маме</label><input id="q" class="input" autofocus></div><button class="primary" onclick="saveQuick()">Добавить</button>`)}
function saveQuick(){const {time,title}=parseQuick(document.querySelector('#q').value.trim());if(!title)return;state.tasks.push({id:uid(),title,date:state.date,time,done:false,important:false,priority:'Средний',groupId:state.groups[0]?.id||null,color:'#2563eb',icon:'✓',repeat:'',comment:''});save();document.querySelector('.modal').remove();app()}
function editTask(id){const t=state.tasks.find(x=>x.id===id)||{id:uid(),title:'',date:state.date,time:'',done:false,important:false,priority:'Средний',groupId:state.groups[0]?.id||'',color:'#2563eb',icon:'✓',repeat:'',comment:''};const fresh=!state.tasks.some(x=>x.id===id);modal(`<div class="between"><h2>${fresh?'Новое дело':'Редактировать'}</h2><button onclick="this.closest('.modal').remove()">✕</button></div><div class="field"><label>Название</label><input id="etitle" class="input" value="${esc(t.title)}"></div><div class="grid"><div class="field"><label>Дата</label><input id="edate" class="input" type="date" value="${t.date}"></div><div class="field"><label>Время</label><input id="etime" class="input" type="time" value="${t.time||''}"></div></div><div class="grid"><div class="field"><label>Группа</label><select id="egroup" class="input">${state.groups.map(g=>`<option value="${g.id}" ${g.id===t.groupId?'selected':''}>${g.icon} ${esc(g.name)}</option>`).join('')}</select></div><div class="field"><label>Приоритет</label><select id="eprio" class="input">${['Низкий','Средний','Высокий'].map(x=>`<option ${x===t.priority?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="field"><label><input id="eimp" type="checkbox" ${t.important?'checked':''}> Важное</label></div><div class="field"><label>Повтор</label><select id="erepeat" class="input"><option value="">Не повторять</option><option ${t.repeat==='Каждый день'?'selected':''}>Каждый день</option><option ${t.repeat==='Каждую неделю'?'selected':''}>Каждую неделю</option><option ${t.repeat==='Каждый месяц'?'selected':''}>Каждый месяц</option><option ${t.repeat==='Каждый год'?'selected':''}>Каждый год</option></select></div><div class="field"><label>Комментарий</label><textarea id="ecomment" rows="3">${esc(t.comment)}</textarea></div><div class="toolbar"><button class="primary" onclick="saveTask('${t.id}',${fresh})">Сохранить</button>${!fresh?`<button class="danger" onclick="delTask('${t.id}')">Удалить</button>`:''}</div>`)}
function saveTask(id,fresh){const t={id,title:document.querySelector('#etitle').value.trim(),date:document.querySelector('#edate').value,time:document.querySelector('#etime').value,groupId:document.querySelector('#egroup').value,priority:document.querySelector('#eprio').value,important:document.querySelector('#eimp').checked,repeat:document.querySelector('#erepeat').value,comment:document.querySelector('#ecomment').value,done:false,color:'#2563eb',icon:'✓'};if(!t.title)return;if(fresh)state.tasks.push(t);else Object.assign(state.tasks.find(x=>x.id===id),t);save();document.querySelector('.modal').remove();app()}
function toggle(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;t.done=!t.done;if(t.done){state.events.push({id:uid(),taskId:id,title:t.title,at:new Date().toISOString()});alert(praise[Math.floor(Math.random()*praise.length)]);if(t.repeat){const d=new Date(t.date+'T12:00');if(t.repeat==='Каждый день')d.setDate(d.getDate()+1);if(t.repeat==='Каждую неделю')d.setDate(d.getDate()+7);if(t.repeat==='Каждый месяц')d.setMonth(d.getMonth()+1);if(t.repeat==='Каждый год')d.setFullYear(d.getFullYear()+1);state.tasks.push({...t,id:uid(),date:iso(d),done:false})}}save();app()}
function delTask(id){state.tasks=state.tasks.filter(t=>t.id!==id);save();document.querySelector('.modal')?.remove();app()}function newNote(){modal(`<h2>Новая заметка</h2><div class="field"><label>Название</label><input id="nt" class="input"></div><div class="field"><label>Текст</label><textarea id="nx" rows="8"></textarea></div><button class="primary" onclick="saveNote()">Сохранить</button>`)}function saveNote(){const title=document.querySelector('#nt').value.trim();if(!title)return;state.notes.push({id:uid(),title,text:document.querySelector('#nx').value,updated:new Date().toISOString()});save();document.querySelector('.modal').remove();app()}function delNote(id){state.notes=state.notes.filter(n=>n.id!==id);save();app()}
function exportData(){const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='MyPlanner-backup.json';a.click()}
window.quick=quick;window.saveQuick=saveQuick;window.setView=setView;window.shift=shift;window.monthShift=monthShift;window.editTask=editTask;window.saveTask=saveTask;window.toggle=toggle;window.delTask=delTask;window.newNote=newNote;window.saveNote=saveNote;window.delNote=delNote;app();
